server:
  host: 54.180.89.196
  port: 8080

spring:
  data:
    mongodb:
      host: 54.180.89.196
      port: 27017
      database: admin
      username: eruty
      password: eruty

  thymeleaf:
    prefix: classpath:/templates/

  mail:
    host: smtp.naver.com
    port: 465
    username: dragonica123@naver.com
    password: (dlsgur46)
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG
