server:
  port: 8080

spring:
  data:
    mongodb:
<<<<<<< Updated upstream
      port: 27017
      host: localhost
      database: ERUTY_Member
      # host: 54.180.89.196
      # database: admin
      # username: eruty
      # password: eruty
=======
      host: localhost
      database: ERUTY_Member
      port: 27017
      #host: 54.180.89.196
      #database: admin
      #username: eruty
      #password: eruty
>>>>>>> Stashed changes

  thymeleaf:
    prefix: classpath:/templates/

  mail:
    host: smtp.naver.com
    port: 465
    username: eruty7057@naver.com
    password: uesung8559??
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

# server:
#   host: 54.180.89.196
#   port: 8080



logging:
  level:
    org.springframework.data.mongodb: DEBUG
