server:
  port: 8234

spring:
  data:
    mongodb:
      host: 54.180.89.196
      port: 27017
      database: admin
      username: eruty
      password: eruty

  thymeleaf:
    prefix: classpath:/templates/

  mail:
    host: smtp.gmail.com
    port: 587
    username: yusung@eruty.co.kr
    password: Uesung8559??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  host: 54.180.89.196
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
