spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ERUTY_Member

  thymeleaf:
    prefix: classpath:/templates/

logging:
  level:
    org.springframework.data.mongodb: DEBUG

