spring:
  data:
    mongodb:
      host: localhost
      #host: 54.180.89.196
      port: 27017
      database: ERUTY_Member
      #database: admin
      #username: eruty
      #password: eruty

  thymeleaf:
    prefix: classpath:/templates/

  mail:
    host: smtp.naver.com
    port: 465
    username: eruty7057@naver.com
    password: uesung8559??
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG
