spring:
  data:
    mongodb:
      port: 27017
      #host: localhost
      #database: ERUTY_Member
      host: 3.36.221.206
      database: admin
      username: eruty
      password: eruty

  thymeleaf:
    prefix: classpath:/templates/

  mail:
    host: smtp.naver.com
    port: 465
    username: eruty201@naver.com
    password: uesung8559??
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG
