spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ERUTY_Member

  thymeleaf:
    prefix: classpath:/templates/

  mail:
    host: smtp.gmail.com
    port: 587
    username: arheon2469@gmail.com
    password: (dlsdnr95)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG

